---
abstract: 'wrap around psgi application to send stuff to raygun.io.'
author:
  - 'Travis Holton <heytrav@cpan.org>'
build_requires:
  HTTP::Request: '0'
  Plack::Test: '0'
  Test::Class: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::MockModule: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-Raygun
requires:
  Plack::Middleware: '0'
  Plack::Util::Accessor: '0'
  Try::Tiny: '0'
  WebService::Raygun::Messenger: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
version: '0.001'
